export const leftStats = [
    { label: "Total P&L", value: "$172,743.11" },
    { label: "Average Daily Volume", value: "$0.05" },
    { label: "Average Winning Trade", value: "$1,583.36", color: "text-green-600" },
    { label: "Average Losing Trade", value: "-$705.32", color: "text-red-500" },
    { label: "Total Trades", value: "765" },
    { label: "Winning Trades", value: "310" },
    { label: "Losing Trades", value: "451" },
    { label: "Break Even Trades", value: "4" },
    { label: "Max Consecutive Wins", value: "19" },
    { label: "Max Consecutive Losses", value: "105" },
    { label: "Commission", value: "-$649.89" },
    { label: "Fees", value: "$1,710.30" },
    { label: "Swap", value: "$0" },
    { label: "Largest Profit", value: "$15,316.26", color: "text-green-600" },
    { label: "Largest Loss", value: "-$10,911.51", color: "text-red-500" },
    { label: "Average Hold Time", value: "1h 28m" },
    { label: "Average Winner Hold", value: "1h 23m" },
    { label: "Average Loser Hold", value: "1h 25m" },
    { label: "Average Scratch Hold", value: "17m" },
    { label: "Average Trade P&L", value: "$89.13" },
    { label: "Profit Factor", value: "1.54" },
  ];
  
  export const rightStats = [
    { label: "Open Trades", value: "0" },
    { label: "Trading Days", value: "140" },
    { label: "Winning Days", value: "83" },
    { label: "Losing Days", value: "55" },
    { label: "Breakeven Days", value: "2" },
    { label: "Logged Days", value: "76" },
    { label: "Max Winning Days", value: "11" },
    { label: "Max Losing Days", value: "21" },
    { label: "Average Daily P&L", value: "$1,244.75" },
    { label: "Average Winning Day", value: "$3,646.33", color: "text-green-600" },
    { label: "Average Losing Day", value: "-$2,334.19", color: "text-red-500" },
    { label: "Largest Winning Day", value: "$29,770" },
    { label: "Largest Losing Day", value: "-$31,695" },
    { label: "Average Planned R", value: "20.45R" },
    { label: "Average Realized R", value: "6.39R" },
    { label: "Trade Expectancy", value: "$226.99" },
    { label: "Max Drawdown", value: "-$64,039", color: "text-red-500" },
    { label: "Max Drawdown %", value: "-226.15%" },
    { label: "Average Drawdown", value: "-$327.75" },
    { label: "Average Drawdown %", value: "-108.36%" },
  ];