export const PlanData = [
  {
    id: 1,
    plan: "Weekly Range",
    category: "Momentum",
    trades: 54,
    winRate: 81.5,
    netPnL: 26000,
    rr: 3.8,
    profitFactor: 4.1,
  },
  {
    id: 2,
    plan: "Breakout",
    category: "Momentum",
    trades: 124,
    winRate: 71.8,
    netPnL: 18000,
    rr: 2.4,
    profitFactor: 2.8,
  },
  {
    id: 3,
    plan: "ICT",
    category: "Smart Money",
    trades: 39,
    winRate: 74.4,
    netPnL: 15000,
    rr: 3.1,
    profitFactor: 3.4,
  },
  {
    id: 4,
    plan: "Pullback",
    category: "Trend",
    trades: 98,
    winRate: 67.3,
    netPnL: 12000,
    rr: 2.1,
    profitFactor: 2.2,
  },
  {
    id: 5,
    plan: "SMC",
    category: "Smart Money",
    trades: 42,
    winRate: 69.0,
    netPnL: 9800,
    rr: 2.2,
    profitFactor: 2.0,
  },
  {
    id: 6,
    plan: "Liquidity Grab",
    category: "Smart Money",
    trades: 31,
    winRate: 71.0,
    netPnL: 8400,
    rr: 2.9,
    profitFactor: 3.0,
  },
  {
    id: 7,
    plan: "Range Break",
    category: "Breakout",
    trades: 47,
    winRate: 63.8,
    netPnL: 7600,
    rr: 2.0,
    profitFactor: 1.9,
  },
  {
    id: 8,
    plan: "Reversal",
    category: "Counter Trend",
    trades: 65,
    winRate: 50.8,
    netPnL: -2000,
    rr: 1.3,
    profitFactor: 0.9,
  },
];